name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build_images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Node Docker Image
        run: docker build elixir/client/ 
      - name: Build Elixir Docker Image
        run: docker build elixir/
  
  test_deployment: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run build script
        run: chmod +x build.sh && ./build.sh 

