name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build_images:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: time_manager
          POSTGRES_USER: postgres
          PGDATA: /var/lib/postgresql/data/pgdata
      
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        
    steps:
      - uses: actions/checkout@v2
      - name: Build Node Docker Image
        run: docker build elixir/client/ 
      - name: Build Elixir Docker Image
        run: docker build elixir/